[package]
name = "build_a_badge"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = "abort"
strip = true


[dependencies]
fwwasm-ffi = {path = "../fwwasm-ffi"}
