[build]
target = "wasm32-unknown-unknown"


[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=-zstack-size=65520",]
runner = "fwi-serial.cmd -mi 1 -fn /scripts/radio.wasm -w radio.wasm -s "